name: Sleeping-Wars-Plugin
version: 1.0-SNAPSHOT
api-version: 1.16
description: Bedwars plugin, customize your own map and set the game system yourself
main: com.joenastan.sleepingwars.SleepingWarsPlugin
author: Joenastan

permissions:
  sleepywar.*:
    description: Sleepywars global permission, every single permission
    children:
      sleepywar.admin: true
      sleepywar.builder: true
      sleepywar.default: true
  sleepywar.builder:
    description: Can edit SleepyWar worlds
    default: op
  sleepywar.default:
    description: Default command for interacting with the plugin
    default: true
  sleepywar.admin:
    description: The game admin, a special permission
    default: op

commands:
  sworld:
    usage: Invalid usage, please consult /help SleepingWars
    permission: sleepywar.default
    description: World maker for Bedwars utility
  bedwars:
    usage: Invalid usage, please consult /help SleepingWars
    permission: sleepywar.default
    description: Play Bedwars (Can only be executed by Administrators)
  swperm:
    usage: Invalid usage, please checkout in /help SleepingWars
    permission: sleepywar.admin
    description: Additional node for managing player permissions