name: SleepingWars
version: 1.0-SNAPSHOT
api-version: 1.16
description: Bedwars plugin, customize your own map and set the game system yourself
main: com.joenastan.sleepingwar.plugin.SleepingWarsPlugin
author: Joenastan

permissions:
    sleepywar.*:
        description: Sleepywars permission, every single permissions
        children:
            sleepywar.sleeper: true
            sleepywar.admin: true
            sleepywar.builder: true
    sleepywar.sleeper.*:
        description: default permission only in bedwars game.
        default: op
        children:
            sleepywar.sleeper.host: true
            sleepywar.sleeper.guest: true
    sleepywar.sleeper.host:
        description: when player just create a game then this perm is now taken.
        default: op
    sleepywar.sleeper.guest:
        description: not much power as host, just join or leave the game.
        default: op
    sleepywar.builder:
        description: can build while in world building.
        default: op
    sleepywar.admin:
        description: the Game Maker, a special permission.
        default: op

commands:
    sworld:
        usage: Invalid usage, please checkout in /help SleepingWars
        permission: sleepywar.admin
        description: World maker for Bedwars utility
    bedwars:
        usage: Invalid usage, please checkout in /help SleepingWars
        permission: sleepywar.sleeper
        description: Play Bedwars (Only can be hosted by admin)
    swperm:
        usage: Invalid usage, please checkout in /help SleepingWars
        permission: sleepywar.admin
        description: Additional for manage player permissions